[package]
name        = "sql-experiments"
description = "Experiments generating SQL in Flix"
version     = "0.1.0"
flix        = "0.66.2"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/flix-rosetree" = { version = "0.2.0", security = "unrestricted" }
"github:stephentetley/flix-pretty" = { version = "0.9.0", security = "unrestricted" }

